controller_manager:
  update_rate: 100
  use_sim_time: true

position_controller:
  type: effort_controllers/JointGroupPositionController
  joints:
    - slider_joint
    - hfe_joint
    - kfe_joint
  slider_joint:
    pid: {p: 1000.0, i: 10000.0, d: 100.0}
  hfe_joint:
    pid: {p: 1000.0, i: 0.0, d: 100.0}
  kfe_joint:
    pid: {p: 1000.0, i: 0.0, d: 100.0}
  
joint_state_controller:
  type: joint_state_controller/JointStateController
  joints:
    - slider_joint
    - hfe_joint
    - kfe_joint
  publish_rate: 100